/**
 * Workflow catalog configuration.
 *
 * Each entry declares a workflow that the user can select. The schema mirrors
 * what the backend's `GET /api/workflows` endpoint is expected to return
 * (see docs/endpoint-contracts.md). At runtime the catalog is fetched via
 * `apiClient.listWorkflows()`; this file is the static fallback used when the
 * backend is unreachable AND `VITE_AUTH_MODE=mock`.
 */
import type { WorkflowDefinition } from '@/types/workflow';

export const WORKFLOW_CATALOG: WorkflowDefinition[] = [
  {
    id: 'support',
    title: 'Support Workflow',
    subtitle: 'Multi-Agent Support — Microsoft Agent Framework',
    description:
      'Triage, KB search, automated resolution, and human handoff for end-user support tickets.',
    icon: 'layers',
    colorTheme: 'primary',
    agents: [
      {
        id: 'triage',
        icon: 'git-branch',
        title: 'Triage Agent',
        description: "Classifies the user's problem and routes to the right agent.",
        colorTheme: 'primary',
        order: 1,
        tools: [],
      },
      {
        id: 'freq',
        icon: 'database',
        title: 'Frequent Problem Agent',
        description: 'Searches KB for known issues. Routes to human when no match.',
        colorTheme: 'warning',
        order: 2,
        tools: [],
      },
      {
        id: 'res',
        icon: 'wrench',
        title: 'Resolution Agent',
        description: 'Executes automated tools to resolve known issues.',
        colorTheme: 'success',
        order: 3,
        tools: ['restart_service', 'reset_password', 'run_diagnostic', 'create_ticket'],
      },
      {
        id: 'pattern',
        icon: 'bar-chart-2',
        title: 'Pattern Record Agent',
        description: 'Records patterns and promotes repeated issues to the KB.',
        colorTheme: 'error',
        order: 4,
        tools: [],
      },
    ],
    scenarios: [
  {
        id: 'known',
        title: 'Known issue',
        label: "Can't login",
        description: 'Authentication problem with KB match and automatic resolution.',
        message: "I can't log in to the system. My password is not working.",
        flowType: 'known',
      },
      {
        id: 'tool',
        title: 'Tool call',
        label: 'Service restart',
        description: 'System availability issue that triggers diagnostics and restart.',
        message: 'The ERP service is not responding. The application is down.',
        flowType: 'tool',
      },
      {
        id: 'human',
        title: 'Unknown',
        label: 'Human handoff',
        description: 'Unknown integration issue escalated to a human agent.',
        message: 'Getting error 0xTISS-4821 during integration sync, never seen this before.',
        flowType: 'human-handoff',
      },
    ],
    capabilities: {
      humanHandoff: true,
      knowledgeBase: true,
      tracing: true,
    },
  },
  {
    id: 'kb-curator',
    title: 'KB Curator',
    subtitle: 'Knowledge base maintenance pipeline',
    description:
      'Reviews ticket history, identifies recurring patterns, and drafts new KB articles for human approval.',
    icon: 'book-open',
    colorTheme: 'success',
    agents: [
      {
        id: 'miner',
        icon: 'pickaxe',
        title: 'Pattern Miner',
        description: 'Finds recurring resolution patterns in closed tickets.',
        colorTheme: 'primary',
        order: 1,
        tools: [],
      },
      {
        id: 'drafter',
        icon: 'pen-line',
        title: 'Article Drafter',
        description: 'Drafts KB articles from clustered tickets.',
        colorTheme: 'success',
        order: 2,
        tools: ['draft_article'],
      },
    ],
    scenarios: [
      {
        id: 'curate',
        title: 'Curate this week',
        label: 'Weekly digest',
        description: 'Mine the last 7 days of tickets and draft article candidates.',
        message: 'Mine the last 7 days of tickets and draft any new KB articles.',
        flowType: 'tool',
      },
    ],
    capabilities: {
      humanHandoff: false,
      knowledgeBase: true,
      tracing: true,
    },
  },
  {
    id: 'vet-assistant',
    title: 'VetAssistant',
    subtitle: 'Assistente Administrativo Veterinário com Triagem Inteligente',
    description:
      'Triagem de urgência, coleta de dados do paciente, agendamento de consultas e vacinas, orientações pós-atendimento e escalonamento para veterinário.',
    icon: 'siren',
    colorTheme: 'success',
    agents: [
      {
        id: 'vet-triage',
        icon: 'git-branch',
        title: 'Triagem de Urgência',
        description: 'Classifica a mensagem por urgência (Emergência / Urgente / Rotina) e tema.',
        colorTheme: 'error',
        order: 1,
        tools: ['ClassifyUrgency', 'DetectAlertSigns'],
      },
      {
        id: 'emergency-escalation',
        icon: 'siren',
        title: 'Escalonamento de Emergência',
        description: 'Envia alerta ao veterinário e mensagem de segurança ao tutor em casos críticos.',
        colorTheme: 'error',
        order: 2,
        tools: ['NotifyVet', 'SendEmergencyMessage'],
      },
      {
        id: 'data-collector',
        icon: 'file-search',
        title: 'Coleta de Dados',
        description: 'Coleta espécie, raça, idade, peso, sintomas, medicação e fotos do paciente.',
        colorTheme: 'primary',
        order: 3,
        tools: ['RequestMissingData', 'ValidatePatientData'],
      },
      {
        id: 'patient-file',
        icon: 'database',
        title: 'Ficha do Paciente',
        description: 'Cria ou atualiza a ficha do animal com histórico completo.',
        colorTheme: 'primary',
        order: 4,
        tools: ['CreateOrUpdatePatientFile', 'SearchPatientHistory'],
      },
      {
        id: 'scheduling',
        icon: 'tag',
        title: 'Agendamento',
        description: 'Agenda consultas, retornos, vacinas, exames e vermifugação.',
        colorTheme: 'success',
        order: 5,
        tools: ['CheckAvailability', 'BookAppointment', 'SetReminder'],
      },
      {
        id: 'post-care',
        icon: 'book-open',
        title: 'Orientações Pós-Consulta',
        description: 'Envia orientações administrativas aprovadas pelo veterinário.',
        colorTheme: 'success',
        order: 6,
        tools: ['GetApprovedInstructions', 'SendPostCareMessage'],
      },
      {
        id: 'vet-handoff',
        icon: 'user-check',
        title: 'Encaminhamento ao Veterinário',
        description: 'Transfere a conversa para o veterinário com contexto completo.',
        colorTheme: 'human',
        order: 7,
        tools: ['PrepareHandoffSummary', 'ActivateHumanMode'],
      },
      {
        id: 'follow-up',
        icon: 'pen-line',
        title: 'Follow-Up',
        description: 'Programa lembretes de evolução, exames e retornos.',
        colorTheme: 'warning',
        order: 8,
        tools: ['ScheduleFollowUp', 'SendFollowUpReminder'],
      },
      {
        id: 'summary',
        icon: 'terminal',
        title: 'Resumo Clínico',
        description: 'Gera resumo estruturado da interação para revisão do veterinário.',
        colorTheme: 'neutral',
        order: 9,
        tools: ['GenerateClinicalSummary', 'UpdatePendingDashboard'],
      },
    ],
    scenarios: [
      {
        id: 'emergencia-convulsao',
        title: 'Emergência',
        label: 'Convulsão',
        description: 'Tutor relata que o animal está tendo convulsões.',
        message: 'Meu cachorro está tendo convulsões agora, não para de tremer e babando muito! O que eu faço?',
        flowType: 'human-handoff',
      },
      {
        id: 'agendar-vacina',
        title: 'Agendamento',
        label: 'Vacina anual',
        description: 'Tutor quer agendar vacina de reforço anual.',
        message: 'Oi, preciso agendar a vacina anual da Luna, ela é uma golden de 3 anos e pesa 28kg. Tem horário essa semana?',
        flowType: 'known',
      },
      {
        id: 'retorno-pos-castracao',
        title: 'Pós-Consulta',
        label: 'Retorno castração',
        description: 'Tutor pede orientações após castração realizada.',
        message: 'O Thor foi castrado ontem e queria saber os cuidados que preciso ter com os pontos e quando retorno.',
        flowType: 'known',
      },
      {
        id: 'sintoma-vomito',
        title: 'Sintoma',
        label: 'Vômito persistente',
        description: 'Tutor relata vômitos repetidos no animal.',
        message: 'Minha gata Mimi de 4 anos está vomitando desde ontem, já foram 4 vezes. Ela comeu ração normal mas está apática e não come.',
        flowType: 'human-handoff',
      },
      {
        id: 'resultado-exame',
        title: 'Exame',
        label: 'Envio de resultado',
        description: 'Tutor envia resultado de exame para avaliação médica.',
        message: 'Doutor, saiu o resultado do hemograma do Bob que o senhor pediu no retorno. Como devo proceder?',
        flowType: 'human-handoff',
      },
    ],
    capabilities: {
      humanHandoff: true,
      knowledgeBase: true,
      tracing: true,
    },
  },
  {
    id: 'sales-assistant',
    title: 'Sales Assistant',
    subtitle: 'Assistente Comercial Inteligente — Microsoft Agent Framework',
    description:
      'Identificação de intenção, busca no catálogo, sugestões de venda cruzada, orçamentos, follow-up e handoff para vendedor.',
    icon: 'tag',
    colorTheme: 'success',
    agents: [
      {
        id: 'intent',
        icon: 'git-branch',
        title: 'Classificador de Intenção',
        description: 'Analisa a mensagem do cliente e classifica a intenção comercial.',
        colorTheme: 'primary',
        order: 1,
        tools: [],
      },
      {
        id: 'catalog',
        icon: 'database',
        title: 'Consultor de Catálogo',
        description: 'Pesquisa produtos por SKU, nome, cor, tamanho e estoque.',
        colorTheme: 'primary',
        order: 2,
        tools: ['SearchProducts', 'CheckStock', 'GetPrice', 'GetProductImage', 'GetCompatibleProducts'],
      },
      {
        id: 'sales-advisor',
        icon: 'pickaxe',
        title: 'Consultor de Vendas',
        description: 'Sugere complementos, alternativas e kits com desconto.',
        colorTheme: 'success',
        order: 3,
        tools: ['GetCompatibleProducts', 'GetPrice'],
      },
      {
        id: 'quote',
        icon: 'file-search',
        title: 'Gerador de Orçamento',
        description: 'Monta proposta comercial formal com preços, descontos e validade.',
        colorTheme: 'warning',
        order: 4,
        tools: ['GenerateQuote', 'ApplyDiscount', 'SendQuote'],
      },
      {
        id: 'follow-up',
        icon: 'pen-line',
        title: 'Agente de Follow-Up',
        description: 'Agenda retorno ao cliente para acompanhar propostas e recuperar carrinhos.',
        colorTheme: 'primary',
        order: 5,
        tools: ['ScheduleFollowUp', 'GetAbandonedCart', 'SendCartReminder'],
      },
      {
        id: 'human-seller',
        icon: 'user-check',
        title: 'Vendedor Humano',
        description: 'Recebe o chat com contexto completo para negociar descontos ou tratar exceções.',
        colorTheme: 'human',
        order: 6,
        tools: [],
      },
      {
        id: 'sales-record',
        icon: 'book-open',
        title: 'Registro de Interação',
        description: 'Consolida métricas e aprendizados da jornada comercial no CRM.',
        colorTheme: 'neutral',
        order: 7,
        tools: [],
      },
    ],
    scenarios: [
      {
        id: 'price-check',
        title: 'Consulta de Preço',
        label: 'Preço de produto',
        description: 'Cliente perguntando o preço de um produto específico.',
        message: 'Quanto custa a camiseta polo azul tamanho M?',
        flowType: 'known',
      },
      {
        id: 'stock-check',
        title: 'Verificar Estoque',
        label: 'Consulta de estoque',
        description: 'Cliente verificando disponibilidade de calçado esportivo.',
        message: 'Vocês têm o tênis Nike Air Max 90 preto número 42 em estoque?',
        flowType: 'known',
      },
      {
        id: 'full-sale',
        title: 'Venda Completa',
        label: 'Jornada completa de compra',
        description: 'Cliente interessado em comprar notebook com orçamento formal.',
        message: 'Estou procurando um notebook para trabalho, preciso de um bom custo-benefício até R$ 4.000. Podem me enviar um orçamento?',
        flowType: 'known',
      },
      {
        id: 'abandoned-cart',
        title: 'Carrinho Abandonado',
        label: 'Recuperação de carrinho',
        description: 'Cliente que abandonou o carrinho retorna para consultar disponibilidade.',
        message: 'Oi, eu tinha colocado uns produtos no carrinho semana passada mas não finalizei. Ainda tem tudo disponível?',
        flowType: 'known',
      },
      {
        id: 'negotiation',
        title: 'Negociação',
        label: 'Pedido de desconto por volume',
        description: 'Cliente quer negociar preço para lote corporativo.',
        message: 'Estou comprando 50 unidades para minha empresa, consigo um desconto especial com vendedor?',
        flowType: 'human-handoff',
      },
      {
        id: 'complaint',
        title: 'Reclamação',
        label: 'Produto divergente',
        description: 'Cliente insatisfeito reportando envio de produto errado.',
        message: 'Recebi o produto errado! Pedi a cor preta e veio azul. Quero resolver isso urgente com um atendente!',
        flowType: 'human-handoff',
      },
    ],
    capabilities: {
      humanHandoff: true,
      knowledgeBase: true,
      tracing: true,
    },
  },
];

